Traceback (most recent call last):
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 649, in writeSpecs
    #Try using dictionary to make decision
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 1134, in <lambda>
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 653, in writeSpecs
    #Have user make a decision and save it to dictionary
        ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 2708, in __init__
    BaseWidget.__init__(self, master, 'toplevel', cnf, {}, extra)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 2659, in __init__
    self.tk.call(
_tkinter.TclError: can't invoke "toplevel" command: application has been destroyed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 1173, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1972, in __call__
    self.widget._report_exception()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1688, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 44, in handle_exception
    top=tk.Toplevel(root)
        ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 2708, in __init__
    BaseWidget.__init__(self, master, 'toplevel', cnf, {}, extra)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 2659, in __init__
    self.tk.call(
_tkinter.TclError: can't invoke "toplevel" command: application has been destroyed
