Traceback (most recent call last):
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 607, in writeSpecs
    specDoc = specDict[str(specData[2])]
              ~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'TTE24C'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 1059, in <lambda>
    submitButton = tk.Button(root, text="Create Specs", command=lambda:writeSpecs(messageLabel))
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 629, in writeSpecs
    t= treeview.insert('', tk.END, text =str(entry[0]), values = (str(entry[1]), str(entry[2]), str(entry[3]).split('/')[len(str(entry[3]).split('/'))],str(entry[3])), tags=("tag?",))
                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
