Traceback (most recent call last):
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 607, in writeSpecs
    specDoc = specDict[str(specData[2])]
              ~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'TTE24C'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 619, in <lambda>
    select = tk.Button(top, text="Select", command=lambda:ChooseSpec(matchedString, top, treeview))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 104, in ChooseSpec
    chosenSpec.set(item['values'][3])
                   ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
